//import localFont from "next/font/local"; //컴퓨터에 있는 폰트 로드
import Link from "next/link";
import "./globals.css";
import Image from "next/image";

/*
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/

export const metadata = {
  title: "Web Tutorials",
  description: "Generated by green-Hongej",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 폰트 로드해서 적용하는 부분 참고
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body> */}
      
      <body>
        <h1>
          <Image src="/home_google_icon.png" alt="home icon" width={48} height={48}></Image>
          <Link href="/">WEB</Link>
        </h1>
        <nav>
          <ol>
            <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
            <li><Link href="/read/3">javascript</Link></li>
          </ol>
        </nav>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><button>delete</button></li>
        </ul>
      </body>
    </html>
  );
}
